[package]
name = "facetty-sfu"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.104"
facetty-proto = { version = "0.2.0", path = "../proto" }
bytes = "1.12.1"
hex = "0.4.3"
quinn = { version = "0.11.12", default-features = false, features = ["runtime-tokio", "rustls-ring", "log"] }
rcgen = "0.14.10"
rustls = { version = "0.23.45", default-features = false, features = ["ring", "std", "logging"] }
sha2 = "0.11.0"
tokio = { version = "1.53.2", features = ["full"] }
tracing = "0.1.44"
